apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kured
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: kured
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "dedicated",
              "operator": "Equal",
              "value": "master",
              "effect": "NoSchedule"
            }
          ]
    spec:
      containers:
        - name: kured
          image: weaveworks/kured
          command:
            - /usr/bin/kured
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: hostrun
              mountPath: /host/var/run
      restartPolicy: Always
      volumes:
        - name: hostrun
          hostPath:
            path: /var/run
